# https://taskfile.dev

version: '3'

tasks:
  default:
    desc: "可用任务列表"
    cmds:
      - task --list
    silent: true
  ready:
    desc: "准备"
    cmds:
      - samea
      - crashu
      - migratef -c -t 'E:\4EHV\already' -d
  add-black:
    desc: "黑名单"
    cmds:
      - samea
      - lista scan --clipboard --category black
      - lista output --category black --format names --overwrite
      - searcha search -c --copy
      - migratef -c -t 'E:\4EHV\trash' -d
  del-black:
    desc: "黑名单"
    cmds:
      # - samea
      - lista output --category black --format names --overwrite
      - searcha search -c --copy
      - migratef -c -t 'E:\4EHV\trash' -d
  ugrep-zip:
    desc: "在 zip 中递归搜索字符串并复制结果到剪贴板 (传入 target= 路径, 否则用默认 E:/4EHV/already)"
    cmds:
      # 用法: task ugrep-zip target=E:\4EHV\already
      # 未提供时使用默认路径 E:/4EHV/already
      - ugrep -L -r -i --include="*.zip" avif "{{.target | default `E:/4EHV/already`}}" | clip
