# https://taskfile.dev

version: '3'

tasks:
  default:
    desc: "可用任务列表"
    cmds:
      - task --list
    silent: true
  ready:
    desc: "准备"
    cmds:
      - samea
      - crashu
      - migratef -c -t 'E:\1Hub\EH\4EHV\already' -d
