# Scoop 环境同步配置
# 运行 utils/scoop_sync.py 同步此清单

[scoop]
root = "D:/scoop"            # 可选：Scoop 根目录，用于 set_env
repo = "https://gitee.com/ScoopInstaller/Scoop"  # 可选：主仓库镜像

[options]
remove_all_before_add = true  # 添加前移除所有已安装 buckets
reset_core_repo = true        # update 前重置核心仓库（git reset/clean）
run_update = true             # 同步后执行 scoop update
set_env = false               # 设置用户环境变量 SCOOP=root
try_fix_ownership = true      # 尝试将相关目录加入 git safe.directory（修复可疑所有权）
dry_run = false               # 仅打印将要执行的命令

# 按顺序声明 buckets
[[bucket]]
name = "main"
url  = "https://gitee.com/scoop-installer/Main"

[[bucket]]
name = "extras"
url  = "https://gitee.com/scoop-installer/Extras"

[[bucket]]
name = "versions"
url  = "https://gitee.com/scoop-installer/Versions"

[[bucket]]
name = "nirsoft"
url  = "https://gitee.com/scoop-installer/Nirsoft"

[[bucket]]
name = "sysinternals"
url  = "https://gitee.com/scoop-installer/scoop-sysinternals"

[[bucket]]
name = "php"
url  = "https://gitee.com/scoop-installer/PHP"

[[bucket]]
name = "nerd-fonts"
url  = "https://gitee.com/scoop-installer/scoop-nerd-fonts"

[[bucket]]
name = "nonportable"
url  = "https://github.com/ScoopInstaller/Nonportable"

[[bucket]]
name = "java"
url  = "https://gitee.com/scoop-installer/Java"

[[bucket]]
name = "games"
url  = "https://gitee.com/scoop-installer/scoop-games"

[[bucket]]
name = "aki"
url  = "https://gitee.com/scoop-installer/aki-apps"

[[bucket]]
name = "cluttered"
url  = "https://gitee.com/scoop-installer/Cluttered-bucket"

[[bucket]]
name = "dorado"
url  = "https://gitee.com/scoop-installer/dorado"

[[bucket]]
name = "echo"
url  = "https://gitee.com/scoop-installer/echo-scoop"

[[bucket]]
name = "iszy"
url  = "https://gitee.com/scoop-installer/scoop-iszy"

[[bucket]]
name = "muggle"
url  = "https://gitee.com/scoop-installer/scoop-muggle"

[[bucket]]
name = "scoop-zapps"
url  = "https://gitee.com/scoop-installer/scoop-zapps"

[[bucket]]
name = "scoopcn"
url  = "https://gitee.com/scoop-installer/scoopcn"

[[bucket]]
name = "scoopet"
url  = "https://gitee.com/scoop-installer/scoopet"

[[bucket]]
name = "sdoog"
url  = "https://gitee.com/scoop-installer/sdoog"

[[bucket]]
name = "siku"
url  = "https://gitee.com/scoop-installer/siku"

[[bucket]]
name = "spc"
url  = "https://gitee.com/wlzwme/scoop-proxy-cn"

[[bucket]]
name = "tomato"
url  = "https://gitee.com/scoop-installer/tomato"
